### Sample routes to test the API

GET http://localhost:3000/api/v1/posts?tag=mongo

###
GET http://localhost:3000/api/v1/posts/{{postId}}

###
POST http://localhost:3000/api/v1/posts
Content-Type: application/json

{
  "title": "Using MongoDB with Node.js",
  "author": "Mongo Team",
  "tags": ["course","learn","mongo"]
}

###
PATCH http://localhost:3000/api/v1/posts/{{postId}}
Content-Type: application/json

{
  "title": "Using MongoDB with Node.js",
  "author": "Mongo Team",
  "contents": "This course guides you through everything you need to get started with MongoDB in your NodeJS applications.",
  "tags": ["course","learn","mongo"]
}

###
DELETE http://localhost:3000/api/v1/posts/{{postId}}

