name: "Modern Full-stack React Projects"
services:
  database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
